### ISSUE TITLE
Generates invalid dts when dashes are used in classNames

### ISSUE THREAD

**Issue by jethrolarson** [Megaputer/dts-css-modules-loader#3] opened 2019-01-17 01:28 UTC
```css
.Tag--locked {
  display: none;
}
```

```TypeScript
export const Tag--locked: string;
```

**Comment by c0gnize** [comment] 2019-01-17 07:29
@jethrolarson, did you use option [camelCase](https://github.com/webpack-contrib/css-loader#camelcase) of the css-loader? It must help.

**Comment by mikecluck** [comment] 2019-01-18 19:14
I did and I'm getting both definitions.

```js
{
    test: /\.css$/,
    use: [
        'style-loader',
        {
            loader: 'dts-css-modules-loader',
            options: {
                banner: '// This file is generated automatically',
                namedExport: true,
            }
        },
        {
            loader: 'css-loader',
            options: {
                modules: true,
                camelCase: true,
                importLoaders: 1,
            }
        }
    ]
}
```

Results in:

```typescript
// This file is generated automatically
export const completion-progress: string;
export const completionProgress: string;
export const form-entry: string;
export const formEntry: string;
```

**Comment by c0gnize** [comment] 2019-01-18 20:34
Now I see. You need to assign `'only'` or `'dashesOnly'` instead of `true` for the `camelCase`.

**Comment by c0gnize** [comment] 2019-01-21 08:31
@jethrolarson if the issue is resolved close it, please.

**Closed as completed** 2019-02-01 16:09 UTC
